version: '3'

services:
    app:
        build: .
        container_name: portfolio_backend
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www
        environment:
            - DB_CONNECTION=sqlite
            - DB_DATABASE=backend.sqlite
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
