version: '3'

services:
    app:
        build: .
        container_name: portfolio_backend
        ports:
            - "80:80"
        volumes:
            - .:/var/www
        environment:
            - DB_CONNECTION=sqlite
            - DB_DATABASE=/var/www/database/backend.sqlite
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
